import { useEffect, useRef, useState } from "react";
import { AppHeader } from "@/components/AppHeader";
import { ChatSidebar } from "@/components/ChatSidebar";
import { MarkdownMessage } from "@/components/MarkdownMessage";
import { Logo } from "@/components/Logo";
import { useAuth } from "@/auth/AuthContext";
import { api, type ChatMessage, type RetrievedChunk } from "@/api/client";

const AI_DISCLAIMER =
  "Answers are generated by AI and can have errors. You are advised to refer to the insurer's policy wordings and T&Cs of all partners.";

interface UIMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  chunks?: RetrievedChunk[];
  streaming?: boolean;
  error?: boolean;
}

interface Suggestion {
  label: string;
  prompt: string;
}

const SUGGESTIONS: Suggestion[] = [
  {
    label: "What does TripSafe cover?",
    prompt: "Give me an overview of what TripSafe travel insurance covers.",
  },
  {
    label: "How do the plans differ?",
    prompt: "How do TripSafe's Silver, Gold and Platinum plans differ?",
  },
  {
    label: "How do I file a claim?",
    prompt: "Walk me through the steps to file a TripSafe claim.",
  },
  {
    label: "Medical emergency coverage?",
    prompt: "What's covered for medical emergencies under TripSafe policies?",
  },
];

export function ChatPage() {
  const [messages, setMessages] = useState<UIMessage[]>([]);
  const [input, setInput] = useState("");
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [sending, setSending] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [sidebarRefresh, setSidebarRefresh] = useState(0);
  const scrollerRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    scrollerRef.current?.scrollTo({
      top: scrollerRef.current.scrollHeight,
      behavior: "smooth",
    });
  }, [messages]);

  useEffect(() => {
    if (!textareaRef.current) return;
    textareaRef.current.style.height = "auto";
    textareaRef.current.style.height = Math.min(textareaRef.current.scrollHeight, 200) + "px";
  }, [input]);

  const startNew = () => {
    setSessionId(null);
    setMessages([]);
    setInput("");
    setSidebarOpen(false);
    setTimeout(() => textareaRef.current?.focus(), 30);
  };

  const loadSession = async (id: string) => {
    if (sending) return;
    setSessionId(id);
    setMessages([]);
    setSidebarOpen(false);
    try {
      const msgs: ChatMessage[] = await api.sessionMessages(id);
      setMessages(
        msgs.map((m) => ({
          id: m.id,
          role: m.role,
          content: m.content,
          chunks: m.retrieved_chunks as RetrievedChunk[] | undefined,
        })),
      );
    } catch {
      setMessages([
        {
          id: crypto.randomUUID(),
          role: "assistant",
          content: "Couldn't load that conversation.",
          error: true,
        },
      ]);
    }
  };

  const send = async (overridePrompt?: string) => {
    const text = (overridePrompt ?? input).trim();
    if (!text || sending) return;
    setInput("");
    const userId = crypto.randomUUID();
    const assistantId = crypto.randomUUID();
    setMessages((m) => [
      ...m,
      { id: userId, role: "user", content: text },
      { id: assistantId, role: "assistant", content: "", streaming: true },
    ]);
    setSending(true);

    let sourcesFromStart: RetrievedChunk[] = [];

    try {
      await api.streamChat(
        { prompt: text, session_id: sessionId },
        {
          onStart: (e) => {
            setSessionId(e.session_id);
            sourcesFromStart = e.sources.map((s) => ({
              source: s.source,
              distance: s.distance,
              text: "",
            }));
          },
          onDelta: (delta) => {
            setMessages((m) =>
              m.map((msg) =>
                msg.id === assistantId ? { ...msg, content: msg.content + delta } : msg,
              ),
            );
          },
          onDone: () => {
            setMessages((m) =>
              m.map((msg) =>
                msg.id === assistantId
                  ? { ...msg, streaming: false, chunks: sourcesFromStart }
                  : msg,
              ),
            );
            setSidebarRefresh((n) => n + 1);
          },
          onError: (detail) => {
            const friendly = detail.includes("Knowledge base not built")
              ? "The knowledge base hasn't been built yet. Ask an admin to upload documents and rebuild the index."
              : detail || "Something went wrong. Try again.";
            setMessages((m) =>
              m.map((msg) =>
                msg.id === assistantId
                  ? { ...msg, content: friendly, streaming: false, error: true }
                  : msg,
              ),
            );
          },
        },
      );
    } catch {
      setMessages((m) =>
        m.map((msg) =>
          msg.id === assistantId
            ? { ...msg, content: "Network error. Please try again.", streaming: false, error: true }
            : msg,
        ),
      );
    } finally {
      setSending(false);
    }
  };

  const onKey = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      void send();
    }
  };

  const isEmpty = messages.length === 0;

  return (
    <div className="h-[100dvh] flex flex-col bg-gray-50 overflow-hidden">
      <AppHeader />
      <div className="flex-1 flex min-h-0 relative">
        <ChatSidebar
          open={sidebarOpen}
          onClose={() => setSidebarOpen(false)}
          activeSessionId={sessionId}
          onSelect={loadSession}
          onNew={startNew}
          refreshKey={sidebarRefresh}
        />

        <main className="flex-1 flex flex-col min-w-0 relative">
          {/* Floating history toggle — anchored to the body, NOT the header */}
          {!sidebarOpen && (
            <button
              onClick={() => setSidebarOpen(true)}
              aria-label="Show chat history"
              title="Chat history"
              className="absolute top-4 left-3 sm:left-4 z-10 h-10 px-3 rounded-full bg-white border border-gray-200 shadow-sm hover:shadow-md hover:border-brand-blue/40 text-gray-700 transition flex items-center gap-2"
            >
              <HistoryIcon />
              <span className="text-sm font-medium hidden sm:inline">History</span>
            </button>
          )}

          <div ref={scrollerRef} className="flex-1 overflow-y-auto scrollbar-thin">
            <div className="max-w-3xl mx-auto w-full px-4 sm:px-6 py-6 pt-20">
              {isEmpty ? (
                <Welcome onPick={(p) => void send(p)} />
              ) : (
                <div className="space-y-5">
                  {messages.map((m) => (
                    <Bubble key={m.id} m={m} />
                  ))}
                </div>
              )}
            </div>
          </div>

          <div className="border-t border-gray-200 bg-white">
            <div className="max-w-3xl mx-auto w-full px-4 sm:px-6 py-3 sm:py-4">
              <div className="flex items-end gap-2 bg-white border border-gray-200 rounded-xl shadow-sm focus-within:border-brand-blue focus-within:ring-2 focus-within:ring-brand-blue/20 transition px-3 py-2">
                <textarea
                  ref={textareaRef}
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={onKey}
                  placeholder="Ask about TripSafe policies, coverage, claims…"
                  rows={1}
                  className="flex-1 resize-none bg-transparent outline-none px-1 py-1.5 max-h-48 placeholder:text-gray-400 leading-relaxed text-base"
                  disabled={sending}
                />
                <button
                  onClick={() => void send()}
                  disabled={!input.trim() || sending}
                  className="h-10 w-10 rounded-full bg-brand-blue text-white flex items-center justify-center shadow-btn disabled:bg-gray-200 disabled:text-gray-400 disabled:cursor-not-allowed disabled:shadow-none hover:bg-brand-navy transition shrink-0"
                  aria-label="Send"
                >
                  {sending ? (
                    <span className="h-4 w-4 border-2 border-current border-r-transparent rounded-full animate-spin" />
                  ) : (
                    <ArrowUpIcon />
                  )}
                </button>
              </div>
              <p className="text-[11px] text-gray-400 mt-2 text-center px-2">
                Answers come from the TripSafe knowledge base. Verify before sharing with customers.
              </p>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}

function Welcome({ onPick }: { onPick: (prompt: string) => void }) {
  return (
    <div className="flex flex-col items-center text-center pt-4 sm:pt-8 pb-8">
      {/* Mark is clipped into a true circle (object-cover) so the PNG's
          white background corners disappear. */}
      <div className="relative mb-6">
        <div
          className="absolute inset-0 rounded-full bg-brand-gradient blur-2xl opacity-25 scale-125"
          aria-hidden
        />
        <div className="relative h-28 w-28 sm:h-32 sm:w-32 rounded-full overflow-hidden bg-white shadow-md ring-1 ring-gray-100">
          <Logo
            variant="mark"
            className="h-full w-full object-cover"
          />
        </div>
      </div>
      <h1 className="text-2xl sm:text-4xl font-semibold text-gray-900 leading-tight px-2">
        How can I help with TripSafe today?
      </h1>
      <p className="text-sm sm:text-base text-gray-500 mt-3 max-w-lg leading-relaxed px-4">
        Ask anything about policy wording, coverage, claims, or eligibility — answers are
        grounded in the latest TripSafe knowledge base.
      </p>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-8 w-full max-w-2xl">
        {SUGGESTIONS.map((s) => (
          <button
            key={s.label}
            onClick={() => onPick(s.prompt)}
            className="text-left px-4 py-3.5 rounded-xl border border-gray-200 bg-white hover:border-brand-blue/40 hover:shadow-md hover:bg-gray-50/50 transition flex items-center gap-3 group"
          >
            <span className="h-1.5 w-1.5 rounded-full bg-brand-blue/60 group-hover:bg-brand-blue shrink-0 transition" />
            <span className="text-sm font-medium text-gray-700 leading-snug flex-1">
              {s.label}
            </span>
            <span className="text-gray-300 group-hover:text-brand-blue group-hover:translate-x-0.5 transition shrink-0">
              <ChevronRightIcon />
            </span>
          </button>
        ))}
      </div>
    </div>
  );
}

function Bubble({ m }: { m: UIMessage }) {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const isUser = m.role === "user";

  if (isUser) {
    return (
      <div className="flex justify-end">
        <div className="max-w-[85%] px-4 py-3 rounded-xl rounded-br-sm bg-brand-blue text-white whitespace-pre-wrap leading-relaxed">
          {m.content}
        </div>
      </div>
    );
  }

  // Dedupe sources by filename. The retriever may pull multiple chunks from
  // the same document — users only need to see each source once, with the
  // count of supporting passages for transparency.
  const uniqueSources = m.chunks
    ? Object.entries(
        m.chunks.reduce<Record<string, number>>((acc, c) => {
          acc[c.source] = (acc[c.source] ?? 0) + 1;
          return acc;
        }, {}),
      ).map(([source, count]) => ({ source, count }))
    : [];

  return (
    <div className="flex justify-start">
      <div className="max-w-[95%] sm:max-w-[92%] w-full">
        <div className="flex gap-3">
          <Logo
            variant="mark"
            className="h-9 w-9 shrink-0 drop-shadow-sm"
          />
          <div
            className={`flex-1 min-w-0 px-4 py-3 rounded-xl rounded-tl-sm border ${
              m.error
                ? "bg-danger-light border-danger/30"
                : "bg-white border-gray-200 shadow-sm"
            }`}
          >
            {m.streaming && m.content.length === 0 ? (
              <TypingDots />
            ) : (
              <>
                <MarkdownMessage text={m.content} />
                {m.streaming && (
                  <span className="inline-block w-2 h-4 bg-brand-blue/60 ml-0.5 animate-pulse align-middle" />
                )}
              </>
            )}

            {!m.error && !m.streaming && m.content && (
              <p className="mt-3 pt-3 border-t border-gray-100 text-[11px] text-gray-400 italic leading-relaxed">
                {AI_DISCLAIMER}
              </p>
            )}

            {isAdmin && uniqueSources.length > 0 && !m.streaming && (
              <details className="mt-2 pt-2 text-xs">
                <summary className="cursor-pointer text-gray-500 select-none hover:text-gray-700">
                  Sources ({uniqueSources.length} {uniqueSources.length === 1 ? "doc" : "docs"})
                </summary>
                <ul className="mt-2 space-y-1.5">
                  {uniqueSources.map((s, i) => (
                    <li key={i} className="text-gray-600 flex items-start gap-2">
                      <span className="text-gray-400 font-mono text-[10px] mt-0.5">{i + 1}.</span>
                      <span className="font-medium text-gray-700 truncate flex-1">
                        {s.source}
                      </span>
                      <span className="text-[10px] text-gray-400 shrink-0">
                        {s.count} {s.count === 1 ? "passage" : "passages"}
                      </span>
                    </li>
                  ))}
                </ul>
              </details>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

function TypingDots() {
  return (
    <div className="flex items-center gap-1 py-1">
      {[0, 1, 2].map((i) => (
        <span
          key={i}
          className="h-2 w-2 bg-brand-blue/60 rounded-full animate-bounce"
          style={{ animationDelay: `${i * 120}ms` }}
        />
      ))}
    </div>
  );
}

// ── Icons ───────────────────────────────────────────────────────────

function ArrowUpIcon() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round">
      <line x1="12" y1="19" x2="12" y2="5" />
      <polyline points="5 12 12 5 19 12" />
    </svg>
  );
}

function HistoryIcon() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
      <path d="M3 12a9 9 0 1 0 9-9 9.7 9.7 0 0 0-6.74 2.74L3 8" />
      <polyline points="3 3 3 8 8 8" />
      <line x1="12" y1="7" x2="12" y2="12" />
      <line x1="12" y1="12" x2="15" y2="14" />
    </svg>
  );
}

function ChevronRightIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="9 18 15 12 9 6" />
    </svg>
  );
}
